### PR TITLE
Structured hint rule implementation

### PR DESCRIPTION
**Pull request by ahlinc**
Screenshot from 2023-03-10 04-46-00

### CODE REVIEW

**Comment by ahlinc** [comment]
Screenshot from 2023-03-10 13-57-08

**Comment by ahlinc** [comment]
Screenshot from 2023-03-10 15-18-18

**Comment by amaanq** [comment]
Sorry just got around to checking this..I'm a bit busy today but I noticed a few files in the Cairo repo fail, can you check them out?

image

Thanks! :)

**Comment by amaanq** [comment]
Thanks again for this! I know it's been a while but this just flew off the radar - I finished the grammar for 0/1 and understand the external scanner better so i'll merge this now w/ my fixes

**Pull request merged**
